site_name: My Docs
theme:
  name: material
  font:
    text: Inter
  palette:
    primary: black
  features:
    - navigation.tabs
    - content.code.copy
    - content.code.select
    - content.code.annotate
extra:
  generator: false
extra_css:
  - stylesheets/globals.css
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
nav:
  - Welcome:
    - welcome/index.md
  - Tutorials:
    - tutorials/index.md
    - Installations:
      - tutorials/installation/linux.md
